<?php
/** React Site Bridge — site documents, media mappings, publishing and export. */
$root = realpath(__DIR__ . '/../../..');
require $root . '/config.php';
require_once dirname(__DIR__) . '/ReactSiteBridgeAPI.php';
Auth::require();
Auth::requirePerm('react-site-bridge.manage');
ReactSiteBridgeAPI::ensureSchema();

$siteId = (int)($_GET['id'] ?? $_POST['site_id'] ?? 0);
$site = ReactSiteBridgeAPI::getSite($siteId);
if (!$site) { http_response_code(404); echo 'React site not found.'; exit; }
$pageTitle = $site['name'] . ' · React Sites';
$currentNav = 'react-site-bridge';
$flash = !empty($_GET['created']) ? ['type' => 'success', 'msg' => 'React site created. Add its route documents and media, then publish.'] : null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_verify()) $flash = ['type' => 'error', 'msg' => __('csrf_failed', 'Security check failed.')];
    else {
        try {
            $action = (string)($_POST['_action'] ?? '');
            if ($action === 'delete_site') {
                ReactSiteBridgeAPI::deleteSite($siteId);
                AuditLog::record('react_site_bridge.site_deleted', 'site#' . $siteId);
                header('Location: ' . SLATE_URL . '/plugins/react-site-bridge/admin/index.php?deleted=1');
                exit;
            } elseif ($action === 'save_site') {
                ReactSiteBridgeAPI::saveSite($siteId, (string)$_POST['name'], (string)$_POST['public_origin'], (string)$_POST['preview_origin']);
                AuditLog::record('react_site_bridge.site_updated', 'site#' . $siteId);
                $flash = ['type' => 'success', 'msg' => 'Site settings saved.'];
            } elseif ($action === 'save_editorial_source') {
                if (!class_exists('ReactSiteBridgeContentBuilder') || !ReactSiteBridgeContentBuilder::available()) throw new RuntimeException('Content Builder must be active before configuring Kaimana Editorial.');
                ReactSiteBridgeContentBuilder::saveSource($siteId, !empty($_POST['editorial_enabled']), (string)($_POST['content_type'] ?? ''), (int)($_POST['item_limit'] ?? 12));
                $published = ReactSiteBridgeAPI::publish($siteId, 'Content Builder editorial source updated.');
                AuditLog::record('react_site_bridge.editorial_source_updated', 'site#' . $siteId . ' v' . $published['version']);
                $flash = ['type' => 'success', 'msg' => 'Kaimana Editorial settings saved and manifest revision v' . $published['version'] . ' published.'];
            } elseif ($action === 'save_document') {
                $id = ReactSiteBridgeAPI::saveDocument($siteId, (int)($_POST['document_id'] ?? 0), (string)$_POST['route'], (string)$_POST['schema_key'], (string)$_POST['document_json'], (string)($_POST['locale'] ?? 'en'));
                AuditLog::record('react_site_bridge.document_saved', 'site#' . $siteId . ' document#' . $id);
                $flash = ['type' => 'success', 'msg' => 'Route document saved as draft.'];
            } elseif ($action === 'delete_document') {
                ReactSiteBridgeAPI::deleteDocument($siteId, (int)$_POST['document_id']);
                AuditLog::record('react_site_bridge.document_deleted', 'site#' . $siteId);
                $flash = ['type' => 'success', 'msg' => 'Route document removed.'];
            } elseif ($action === 'save_media') {
                $id = ReactSiteBridgeAPI::saveMediaMapping($siteId, (int)($_POST['mapping_id'] ?? 0), (string)$_POST['logical_key'], (int)$_POST['media_id'], (string)$_POST['alt_text'], $_POST['focal_x'] ?? null, $_POST['focal_y'] ?? null);
                AuditLog::record('react_site_bridge.media_saved', 'site#' . $siteId . ' mapping#' . $id);
                $flash = ['type' => 'success', 'msg' => 'Media mapping saved as draft.'];
            } elseif ($action === 'delete_media') {
                ReactSiteBridgeAPI::deleteMediaMapping($siteId, (int)$_POST['mapping_id']);
                AuditLog::record('react_site_bridge.media_deleted', 'site#' . $siteId);
                $flash = ['type' => 'success', 'msg' => 'Media mapping removed.'];
            } elseif ($action === 'publish') {
                if (!Auth::can('react-site-bridge.publish') && !Auth::isSuperAdmin()) throw new RuntimeException('You do not have permission to publish React site revisions.');
                $published = ReactSiteBridgeAPI::publish($siteId, (string)($_POST['note'] ?? ''));
                AuditLog::record('react_site_bridge.published', 'site#' . $siteId . ' v' . $published['version']);
                $flash = ['type' => 'success', 'msg' => 'Published manifest revision v' . $published['version'] . '.'];
            } elseif ($action === 'export_seed') {
                $seed = ReactSiteBridgeAPI::exportSeed($siteId);
                header('Content-Type: application/json; charset=utf-8');
                header('Content-Disposition: attachment; filename="' . preg_replace('/[^a-z0-9-]+/', '-', strtolower($site['site_key'])) . '-site-bridge-seed.json"');
                echo json_encode($seed, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
                exit;
            }
        } catch (Throwable $e) { $flash = ['type' => 'error', 'msg' => $e->getMessage()]; }
    }
    $site = ReactSiteBridgeAPI::getSite($siteId) ?: $site;
}

$documents = ReactSiteBridgeAPI::listDocuments($siteId);
$mappings = ReactSiteBridgeAPI::listMediaMappings($siteId);
$hostedUrl = ReactSiteBridgeAPI::hostedUrl($siteId);
$media = class_exists('Media') ? Media::listAll(['type' => 'image', 'per_page' => 200])['items'] : [];
$editDocument = !empty($_GET['edit_document']) ? ReactSiteBridgeAPI::getDocument($siteId, (int)$_GET['edit_document']) : null;
$editDocumentJson = $editDocument ? json_encode($editDocument['document'], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) : "{\n  \n}";
$editorialAvailable = class_exists('ReactSiteBridgeContentBuilder') && ReactSiteBridgeContentBuilder::available();
$editorialSource = $editorialAvailable ? ReactSiteBridgeContentBuilder::getSource($siteId) : null;
$editorialUrl = rtrim(SLATE_URL, '/') . '/plugins/content-builder/admin/posts.php?type=kaimana-editorial';
require $root . '/admin/partials/header.php';
?>
<?php slate_breadcrumbs([['label' => __('dashboard', 'Dashboard'), 'href' => SLATE_URL . '/admin/'], ['label' => 'React Sites', 'href' => SLATE_URL . '/plugins/react-site-bridge/admin/index.php'], ['label' => $site['name']]]); ?>
<?php $manifestUrl = rtrim(SLATE_URL, '/') . '/site-data/' . rawurlencode((string)$site['public_id']) . '/manifest'; $frontendUrl = (string)($site['preview_origin'] ?: $site['public_origin']); $previewUrl = rtrim(SLATE_URL, '/') . '/react-preview/' . rawurlencode((string)$site['public_id']); ?>
	<div class="page-header"><div><h1><?= e($site['name']) ?></h1><p class="page-header-sub">Static React frontend · <?= e($site['site_key']) ?> · <?= e($site['status']) ?></p></div><div class="rsc-header-actions"><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/index.php') ?>">All sites</a><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/content.php?id=' . $siteId) ?>">Content editor</a><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/photography.php?id=' . $siteId) ?>">Approved photography</a><?php if ($hostedUrl): ?><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/visual.php?id=' . $siteId) ?>">Visual editor</a><?php endif; ?><?php if ($editorialAvailable): ?><a class="btn btn-secondary" href="<?= e($editorialUrl) ?>">Kaimana Editorial</a><?php endif; ?><?php if (!empty($site['active_revision_id'])): ?><a class="btn btn-secondary" target="_blank" rel="noopener" href="<?= e($manifestUrl) ?>">View manifest</a><?php endif; ?><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/hosting.php?id=' . $siteId) ?>">Hosted release</a><?php if ($hostedUrl): ?><a class="btn btn-primary" target="_blank" rel="noopener" href="<?= e($hostedUrl) ?>">Open Slate-hosted site</a><?php elseif ($frontendUrl): ?><a class="btn btn-primary" target="_blank" rel="noopener" href="<?= e($previewUrl) ?>">Preview frontend</a><?php endif; ?></div></div>
<?php if ($flash): ?><div class="alert alert-<?= e($flash['type']) ?>" role="status"><?= e($flash['msg']) ?></div><?php endif; ?>
<div class="rsc-tabs"><a href="#settings">Settings</a><a href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/content.php?id=' . $siteId) ?>">Content editor</a><?php if ($hostedUrl): ?><a href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/visual.php?id=' . $siteId) ?>">Visual editor</a><?php endif; ?><?php if ($editorialAvailable): ?><a href="#editorial">Kaimana Editorial</a><?php endif; ?><a href="#documents">Route documents</a><a href="#media">Media</a><a href="#publish">Publish</a><a href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/hosting.php?id=' . $siteId) ?>">Hosted release</a></div>
<section id="settings" class="card rsc-section"><div class="card-header"><h2>Site settings</h2></div><form method="post"><input type="hidden" name="_action" value="save_site"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><div class="rsc-grid"><div class="field"><label class="field-label">Name</label><input name="name" required value="<?= e($site['name']) ?>"></div><div class="field"><label class="field-label">Public identifier</label><input readonly value="<?= e($site['public_id']) ?>"><p class="field-help">Configure this value in the React build as its public bridge identifier.</p></div><div class="field"><label class="field-label">Published frontend origin</label><input type="url" name="public_origin" value="<?= e((string)$site['public_origin']) ?>" placeholder="https://www.example.com"></div><div class="field"><label class="field-label">Preview frontend origin</label><input type="url" name="preview_origin" value="<?= e((string)$site['preview_origin']) ?>" placeholder="https://preview.example.com"></div></div><button class="btn btn-primary" type="submit">Save settings</button></form><?php if ($frontendUrl): ?><p class="field-help rsc-preview-help">Slate preview link: <a target="_blank" rel="noopener" href="<?= e($previewUrl) ?>"><?= e($previewUrl) ?></a></p><?php else: ?><p class="field-help rsc-preview-help">To open a rendered preview, deploy the React build to a preview URL and save that URL above. Until then, use <a target="_blank" rel="noopener" href="<?= e($manifestUrl) ?>">View manifest</a> to confirm published content.</p><?php endif; ?><form method="post" class="rsc-danger-zone" onsubmit="return confirm('Delete this React site and all of its bridge documents, mappings, and manifest revisions? Media Library files are retained.');"><input type="hidden" name="_action" value="delete_site"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><button class="btn btn-sm btn-danger" type="submit">Delete React site</button><span>Removes this site record and its bridge content; Media Library files remain available.</span></form></section>
<?php if ($editorialAvailable): ?><section id="editorial" class="card rsc-section"><div class="card-header"><h2>Kaimana Editorial</h2></div><p>Use Content Builder for future stories, project context, and resource articles. It does not change the protected Kaimana page layouts or the structured copy controlled by <strong>Content editor</strong>.</p><form method="post"><input type="hidden" name="_action" value="save_editorial_source"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><input type="hidden" name="content_type" value="kaimana-editorial"><div class="rsc-grid"><div class="field"><label class="field-label"><input type="checkbox" name="editorial_enabled" value="1" <?= !empty($editorialSource['enabled']) ? 'checked' : '' ?>> Include published Kaimana Editorial items in the public React manifest</label><p class="field-help">When enabled, published items appear on the new React editorial route. Core Kaimana pages remain protected.</p></div><div class="field"><label class="field-label">Maximum published items</label><input type="number" name="item_limit" min="1" max="30" value="<?= (int)($editorialSource['item_limit'] ?? 12) ?>"><p class="field-help">Use Content Builder’s title, excerpt, heading, paragraph, image, and button blocks. Raw HTML is never transferred to React.</p></div></div><div class="rsc-actions"><button class="btn btn-primary" type="submit">Save editorial settings &amp; publish</button><a class="btn btn-secondary" href="<?= e($editorialUrl) ?>">Manage Kaimana Editorial</a></div></form></section><?php endif; ?>
<section id="documents" class="card rsc-section"><div class="card-header"><h2><?= $editDocument ? 'Edit route document' : 'Add route document' ?></h2></div><form method="post"><input type="hidden" name="_action" value="save_document"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><input type="hidden" name="document_id" value="<?= (int)($editDocument['id'] ?? 0) ?>"><div class="rsc-grid"><div class="field"><label class="field-label">Route</label><input name="route" required value="<?= e((string)($editDocument['route'] ?? '/')) ?>" placeholder="/electric"></div><div class="field"><label class="field-label">Schema key</label><input name="schema_key" value="<?= e((string)($editDocument['schema_key'] ?? '')) ?>" placeholder="kaimana.electric.v1"></div><div class="field"><label class="field-label">Locale</label><input name="locale" maxlength="16" value="<?= e((string)($editDocument['locale'] ?? 'en')) ?>"></div></div><div class="field"><label class="field-label">Document JSON</label><textarea class="rsc-code" name="document_json" required rows="14"><?= e($editDocumentJson) ?></textarea><p class="field-help">This is the structured data read by the React page. Layout and component code remain in the React release.</p></div><button class="btn btn-primary" type="submit">Save draft</button><?php if ($editDocument): ?><a class="btn btn-secondary" href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/site.php?id=' . $siteId) ?>">Cancel</a><?php endif; ?></form>
  <?php if ($documents): ?><div class="rsc-list"><h3>Saved documents</h3><?php foreach ($documents as $document): ?><div class="rsc-row"><div><strong><?= e($document['route']) ?></strong><span><?= e($document['schema_key'] ?: 'No schema') ?> · <?= e($document['locale']) ?></span></div><div><a class="btn btn-sm" href="?id=<?= $siteId ?>&edit_document=<?= (int)$document['id'] ?>">Edit</a><form method="post" class="inline-form" onsubmit="return confirm('Remove this route document?');"><?= csrf_field() ?><input type="hidden" name="_action" value="delete_document"><input type="hidden" name="site_id" value="<?= $siteId ?>"><input type="hidden" name="document_id" value="<?= (int)$document['id'] ?>"><button class="btn btn-sm btn-danger">Remove</button></form></div></div><?php endforeach; ?></div><?php endif; ?></section>
<section id="media" class="card rsc-section"><div class="card-header"><h2>Media mappings</h2></div><form method="post"><input type="hidden" name="_action" value="save_media"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><input type="hidden" name="mapping_id" value="0"><div class="rsc-grid"><div class="field"><label class="field-label">Logical key</label><input name="logical_key" required placeholder="kaimana.electric.hero"></div><div class="field"><label class="field-label">Media library image</label><select name="media_id" required><option value="">Select an image</option><?php foreach ($media as $item): ?><option value="<?= (int)$item['id'] ?>"><?= e((string)($item['original_name'] ?? $item['path'])) ?></option><?php endforeach; ?></select></div><div class="field"><label class="field-label">Alternative text</label><input name="alt_text" maxlength="500" placeholder="Describe the image for assistive technology"></div><div class="field"><label class="field-label">Focal point</label><div class="rsc-inline"><input type="number" name="focal_x" min="0" max="1" step="0.01" placeholder="X 0–1"><input type="number" name="focal_y" min="0" max="1" step="0.01" placeholder="Y 0–1"></div></div></div><button class="btn btn-primary" type="submit">Save media mapping</button></form>
	<p class="field-help rsc-media-workflow"><strong>Adding approved photography?</strong> Use the guided <a href="<?= e(SLATE_URL . '/plugins/react-site-bridge/admin/photography.php?id=' . $siteId) ?>">upload and map workflow</a> to register it through Slate Media, write accessible text, and expose it to the visual editor as a draft mapping.</p><?php if ($mappings): ?><div class="rsc-list"><h3>Current mappings</h3><?php foreach ($mappings as $mapping): ?><div class="rsc-row"><div><strong><?= e($mapping['logical_key']) ?></strong><span><?= e((string)($mapping['media']['original_name'] ?? 'Missing media')) ?><?= $mapping['alt_text'] ? ' · ' . e($mapping['alt_text']) : '' ?></span></div><form method="post" class="inline-form" onsubmit="return confirm('Remove this media mapping?');"><?= csrf_field() ?><input type="hidden" name="_action" value="delete_media"><input type="hidden" name="site_id" value="<?= $siteId ?>"><input type="hidden" name="mapping_id" value="<?= (int)$mapping['id'] ?>"><button class="btn btn-sm btn-danger">Remove</button></form></div><?php endforeach; ?></div><?php endif; ?></section>
<section id="publish" class="card rsc-section"><div class="card-header"><h2>Publish and export</h2></div><p>Publishing captures the current route documents and media mappings in an immutable public manifest. Existing published visitors continue to receive the previous manifest until you publish a new revision.</p><div class="rsc-actions"><form method="post"><input type="hidden" name="_action" value="publish"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><input class="rsc-note" name="note" maxlength="500" placeholder="Release note (optional)"><button class="btn btn-primary" type="submit">Publish manifest</button></form><form method="post"><input type="hidden" name="_action" value="export_seed"><?= csrf_field() ?><input type="hidden" name="site_id" value="<?= $siteId ?>"><button class="btn btn-secondary" type="submit">Export seed JSON</button></form></div><?php if (!empty($site['active_revision_id'])): ?><p class="field-help">Published manifest: <code><?= e(rtrim(SLATE_URL, '/') . '/site-data/' . $site['public_id'] . '/manifest') ?></code></p><?php endif; ?></section>
	<style>.rsc-section{margin-bottom:18px}.rsc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.rsc-tabs,.rsc-header-actions{display:flex;gap:10px;flex-wrap:wrap;margin:0 0 18px}.rsc-tabs a{font-size:.9rem}.rsc-header-actions{margin:0;justify-content:flex-end}.rsc-code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;min-height:250px}.field-help{margin:5px 0 0;font-size:.82rem;color:var(--muted,#6b7280)}.rsc-media-workflow{margin-top:14px;padding:10px 12px;border-left:3px solid var(--primary,#2563eb);background:var(--surface-alt,#f8fafc)}.rsc-preview-help{margin-top:15px}.rsc-danger-zone{display:flex;align-items:center;gap:10px;margin-top:20px;padding-top:16px;border-top:1px solid var(--border,#e5e7eb)}.rsc-danger-zone span{font-size:.82rem;color:var(--muted,#6b7280)}.rsc-list{margin-top:22px;border-top:1px solid var(--border,#e5e7eb)}.rsc-list h3{font-size:1rem;margin:16px 0}.rsc-row{display:flex;justify-content:space-between;gap:14px;padding:12px 0;border-top:1px solid var(--border,#e5e7eb)}.rsc-row:first-of-type{border-top:0}.rsc-row strong,.rsc-row span{display:block}.rsc-row span{font-size:.84rem;color:var(--muted,#6b7280);margin-top:3px}.inline-form{display:inline-block;margin-left:6px}.rsc-inline{display:flex;gap:8px}.rsc-actions{display:flex;gap:10px;flex-wrap:wrap;align-items:end}.rsc-note{margin-right:8px;min-width:220px}@media(max-width:720px){.rsc-grid{grid-template-columns:1fr}.rsc-header-actions{justify-content:flex-start;margin-top:12px}.rsc-row{display:block}.rsc-row>div:last-child,.rsc-row>form{margin-top:10px}.rsc-note{width:100%;margin:0 0 8px}.rsc-danger-zone{display:block}.rsc-danger-zone span{display:block;margin-top:8px}}</style>
<?php require $root . '/admin/partials/footer.php'; ?>
